---
grails:
    profile: web
    codegen:
        defaultPackage: traderapp
    spring:
        transactionManagement:
            proxies: false
    gorm:
        # Whether to autowire entities.
        # Disabled by default for performance reasons.
        autowire: true
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false

#Mail Configuration
environments:
    development:
        grails:
            mail:
                host: "smtp.gmail.com"
                port: 465
                username: "dev.prospera@gmail.com"
                password: "Abcd0000"
                overrideAddress: "dev.prospera@gmail.com"
                props:
                    mail.smtp.auth: "true"
                    mail.smtp.socketFactory.port: "465"
                    mail.smtp.socketFactory.class: "javax.net.ssl.SSLSocketFactory"
                    mail.smtp.socketFactory.fallback: "false"
    test:
        grails:
            mail:
                host: "smtp.gmail.com"
                port: 465
                username: "dev.prospera@gmail.com"
                password: "Abcd0000"
                props:
                    mail.smtp.auth: "true"
                    mail.smtp.socketFactory.port: "465"
                    mail.smtp.socketFactory.class: "javax.net.ssl.SSLSocketFactory"
                    mail.smtp.socketFactory.fallback: "false"
    production:
        grails:
            mail:
                host: "smtp.gmail.com"
                port: 465
                username: "dev.prospera@gmail.com"
                password: "Abcd0000"
                props:
                    mail.smtp.auth: "true"
                    mail.smtp.socketFactory.port: "465"
                    mail.smtp.socketFactory.class: "javax.net.ssl.SSLSocketFactory"
                    mail.smtp.socketFactory.fallback: "false"

info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

#Setting context of application
server:
    contextPath: '/'

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---

grails:
    controllers:
        upload:
          maxFileSize: 26214400
          maxRequestSize: 26214400

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    username: root
    password: root

environments:
    development:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost/traderapp?useUnicode=yes&characterEncoding=UTF-8
    test:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://traderefer.ccrltwtjkuil.us-east-2.rds.amazonaws.com:3306/traderapp?useUnicode=yes&characterEncoding=UTF-8
            username: "traderapp_test"
            password: "traderapp_test"
            properties:
                minEvictableIdleTimeMillis: 1800000
                timeBetweenEvictionRunsMillis: 1800000
                numTestsPerEvictionRun: 3
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: true
                validationQuery: SELECT 1
    production:
        dataSource:
            dbCreate: none
            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
